<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="8" passed="5" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-05-22T13:49:14Z" name="MyAutomation Suite" finished-at="2024-05-22T13:49:29Z" duration-ms="14455">
    <groups>
    </groups>
    <test started-at="2024-05-22T13:49:14Z" name="MyAutomation tests" finished-at="2024-05-22T13:49:29Z" duration-ms="14455">
      <class name="Tests.False_Test">
        <test-method is-config="true" signature="setup()[pri:0, instance:Tests.False_Test@79ad8b2f]" started-at="2024-05-22T13:49:22Z" name="setup" finished-at="2024-05-22T13:49:26Z" duration-ms="4346" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="First_False_Test()[pri:0, instance:Tests.False_Test@79ad8b2f]" started-at="2024-05-22T13:49:26Z" name="First_False_Test" description="click on upper menu with one string" finished-at="2024-05-22T13:49:26Z" duration-ms="1" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at Tests.False_Test.First_False_Test(False_Test.java:14)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- First_False_Test -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:Tests.False_Test@79ad8b2f]" started-at="2024-05-22T13:49:26Z" name="afterMethod" finished-at="2024-05-22T13:49:27Z" duration-ms="604" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=First_False_Test status=FAILURE method=False_Test.First_False_Test()[pri:0, instance:Tests.False_Test@79ad8b2f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="Forth_False_Test()[pri:0, instance:Tests.False_Test@79ad8b2f]" started-at="2024-05-22T13:49:27Z" name="Forth_False_Test" description="click on upper menu with one string" finished-at="2024-05-22T13:49:27Z" duration-ms="2" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at Tests.False_Test.Forth_False_Test(False_Test.java:32)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Forth_False_Test -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:Tests.False_Test@79ad8b2f]" started-at="2024-05-22T13:49:27Z" name="afterMethod" finished-at="2024-05-22T13:49:28Z" duration-ms="1385" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Forth_False_Test status=FAILURE method=False_Test.Forth_False_Test()[pri:0, instance:Tests.False_Test@79ad8b2f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="Second_False_Test()[pri:0, instance:Tests.False_Test@79ad8b2f]" started-at="2024-05-22T13:49:28Z" name="Second_False_Test" description="click on upper menu with one string" finished-at="2024-05-22T13:49:28Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Second_False_Test -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:Tests.False_Test@79ad8b2f]" started-at="2024-05-22T13:49:28Z" name="afterMethod" finished-at="2024-05-22T13:49:28Z" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Second_False_Test status=SUCCESS method=False_Test.Second_False_Test()[pri:0, instance:Tests.False_Test@79ad8b2f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="Third_False_Test()[pri:0, instance:Tests.False_Test@79ad8b2f]" started-at="2024-05-22T13:49:28Z" name="Third_False_Test" description="click on upper menu with one string" finished-at="2024-05-22T13:49:28Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Third_False_Test -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:Tests.False_Test@79ad8b2f]" started-at="2024-05-22T13:49:28Z" name="afterMethod" finished-at="2024-05-22T13:49:28Z" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Third_False_Test status=SUCCESS method=False_Test.Third_False_Test()[pri:0, instance:Tests.False_Test@79ad8b2f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="quitDriver()[pri:0, instance:Tests.False_Test@79ad8b2f]" started-at="2024-05-22T13:49:28Z" name="quitDriver" finished-at="2024-05-22T13:49:29Z" duration-ms="726" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- Tests.False_Test -->
      <class name="Tests.True_Test">
        <test-method is-config="true" signature="setup()[pri:0, instance:Tests.True_Test@402e37bc]" started-at="2024-05-22T13:49:14Z" name="setup" finished-at="2024-05-22T13:49:21Z" duration-ms="6824" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="First_True_Test()[pri:0, instance:Tests.True_Test@402e37bc]" started-at="2024-05-22T13:49:21Z" name="First_True_Test" description="verify table cell text" finished-at="2024-05-22T13:49:21Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- First_True_Test -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:Tests.True_Test@402e37bc]" started-at="2024-05-22T13:49:21Z" name="afterMethod" finished-at="2024-05-22T13:49:21Z" duration-ms="3" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=First_True_Test status=SUCCESS method=True_Test.First_True_Test()[pri:0, instance:Tests.True_Test@402e37bc] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="Forth_True_Test()[pri:0, instance:Tests.True_Test@402e37bc]" started-at="2024-05-22T13:49:21Z" name="Forth_True_Test" description="click on upper menu with one string" finished-at="2024-05-22T13:49:21Z" duration-ms="3" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at Tests.True_Test.Forth_True_Test(True_Test.java:33)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Forth_True_Test -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:Tests.True_Test@402e37bc]" started-at="2024-05-22T13:49:21Z" name="afterMethod" finished-at="2024-05-22T13:49:21Z" duration-ms="229" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Forth_True_Test status=FAILURE method=True_Test.Forth_True_Test()[pri:0, instance:Tests.True_Test@402e37bc] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="Second_True_Test()[pri:0, instance:Tests.True_Test@402e37bc]" started-at="2024-05-22T13:49:21Z" name="Second_True_Test" description="verify table cell text" finished-at="2024-05-22T13:49:21Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Second_True_Test -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:Tests.True_Test@402e37bc]" started-at="2024-05-22T13:49:21Z" name="afterMethod" finished-at="2024-05-22T13:49:21Z" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Second_True_Test status=SUCCESS method=True_Test.Second_True_Test()[pri:0, instance:Tests.True_Test@402e37bc] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:Tests.True_Test@402e37bc]" started-at="2024-05-22T13:49:21Z" name="afterMethod" finished-at="2024-05-22T13:49:21Z" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Third_True_Test status=SUCCESS method=True_Test.Third_True_Test()[pri:0, instance:Tests.True_Test@402e37bc] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="Third_True_Test()[pri:0, instance:Tests.True_Test@402e37bc]" started-at="2024-05-22T13:49:21Z" name="Third_True_Test" description="click on upper menu with one string" finished-at="2024-05-22T13:49:21Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Third_True_Test -->
        <test-method is-config="true" signature="quitDriver()[pri:0, instance:Tests.True_Test@402e37bc]" started-at="2024-05-22T13:49:21Z" name="quitDriver" finished-at="2024-05-22T13:49:22Z" duration-ms="245" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- Tests.True_Test -->
    </test> <!-- MyAutomation tests -->
  </suite> <!-- MyAutomation Suite -->
</testng-results>
